---
title: "Data Analysis"
author: "Abby Wallace, Lisa Woelfl, Torrence Banks, Noah Ferguson"
date: "11/11/2022"
output:
  html_document:
    theme: cerulean
    highlight: pygments
    toc: true
    toc_float:
      collapsed: true
      smooth_scroll: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction 

In this notebook, we are analysing data from the Maryland Lobbying Registrations. [https://lobby-ethics.maryland.gov/]

## Load libraries

Loading required libraries for this analysis.

```{r echo=FALSE, message=FALSE}
# Load the tidyverse here
library(tidyverse)
# Load janitor here
library(janitor)
library(lubridate)
```

## Load and Cleaning Data

```{r}
# Load required data
# Path to data should be loaded from folder "data" i.e. read_csv("data/name_of_data.csv")

# Clean required data and prepare for analysis if needed. 


```

## Basic explorations

*How many rows & columns?
*What are limitations & flaws?


### Question 1

* **Question text**: 
* **Analysis summary**:
